apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/redhat-cop/gitops-catalog/openshift-pipelines-operator/overlays/stable?ref=main

commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
