apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    opendatahub.io/dashboard: "true"
  name: jupyterhub-nb-{{ .Values.user_urlencoded }}-pvc
  namespace: rhods-notebooks
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: { { .Values.notebook.storage.class } }
  volumeMode: Filesystem
