apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  labels:
    opendatahub.io/dashboard: "true"
  name: jupyter-nb-place-2dholder-notebook-view
  namespace: rhods-notebooks
rules:
- apiGroups:
  - kubeflow.org
  resourceNames:
  - jupyter-nb-place-2dholder
  resources:
  - notebooks
  verbs:
  - get