cluster_name         = "rosa-rcarrata"
replicas             = "3"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  # Worker replicas. Set to 3 for HA, 2 for single-AZ
offline_access_token = "eyJhbGciOiJIUzI1NiIsInR5cCIgOiAiSldUIiwia2lkIiA6ICJhZDUyMjdhMy1iY2ZkLTRjZjAtYTdiNi0zOTk4MzVhMDg1NjYifQ.eyJpYXQiOjE2OTQwMDIyNjYsImp0aSI6IjZlMmYwMzc1LThlNWEtNDNkMC1iMWJmLWJjOTI3ZDYzNzAzMSIsImlzcyI6Imh0dHBzOi8vc3NvLnJlZGhhdC5jb20vYXV0aC9yZWFsbXMvcmVkaGF0LWV4dGVybmFsIiwiYXVkIjoiaHR0cHM6Ly9zc28ucmVkaGF0LmNvbS9hdXRoL3JlYWxtcy9yZWRoYXQtZXh0ZXJuYWwiLCJzdWIiOiJmOjUyOGQ3NmZmLWY3MDgtNDNlZC04Y2Q1LWZlMTZmNGZlMGNlNjpyY2FycmF0YUByZWRoYXQuY29tIiwidHlwIjoiT2ZmbGluZSIsImF6cCI6ImNsb3VkLXNlcnZpY2VzIiwibm9uY2UiOiIzZmI4YWY4ZC1hOGQ1LTRkZWYtYTEwNy02ZjdjZWQ4YWVlNTciLCJzZXNzaW9uX3N0YXRlIjoiMmE2MmNmNTEtNDMzNC00YzgzLWJmOTMtNTA1MGVmMzBhYzZmIiwic2NvcGUiOiJvcGVuaWQgYXBpLmlhbS5zZXJ2aWNlX2FjY291bnRzIG9mZmxpbmVfYWNjZXNzIiwic2lkIjoiMmE2MmNmNTEtNDMzNC00YzgzLWJmOTMtNTA1MGVmMzBhYzZmIn0.-ipg3ha2gnWWiL-ccGeixSq12ev_Hq6ZVEvKkb8dFbw" # Get from https://console.redhat.com/openshift/token/rosa/show
rosa_version         = "4.13.11"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            # Needs to be a supported version by ROSA
aws_region           = "eu-west-1"                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          # Optional, only if you're not selecting us-west-2 region
# availability_zones   = ["eu-west-1a", "eu-west-1b", "eu-west-1c"]

# Only for single-AZ                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                           # Optional, only if you're not selecting us-west-2 region
availability_zones   = ["eu-west-1a"]
private_subnet_cidrs = ["10.66.1.0/24"]
public_subnet_cidrs  = ["10.66.101.0/24"]

htpasswd_username = "cluster-admin"
htpasswd_password = "pGhCferyH!9Ut*"

#machine_type        = "g5.xlarge"
machine_type        = "g4dn.2xlarge"
machineset_replicas = "1"
#machineset_replicas = "3"
multi_availability_zone = false
use_spot_instances      = true
