apiVersion: kfdef.apps.kubeflow.org/v1
kind: KfDef
metadata:
  name: codeflare-stack
  namespace: odh
spec:
  applications:
    # CodeFlare
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: codeflare-stack
      name: codeflare-stack
    # KubeRay
    - kustomizeConfig:
        repoRef:
          name: manifests
          path: ray/operator
      name: ray-operator
  repos:
    # ODH Core component manifests
    - name: manifests
      uri: https://github.com/mamurak/distributed-workloads/tarball/main
