apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: operators-odh-appset
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource
spec:
  generators:
    - git:
        repoURL: https://github.com/rcarrat-AI/nvidia-odh-gitops
        revision: main
        directories:
          - path: templates/odh/*
  template:
    metadata:
      name: "{{path.basename}}"
    spec:
      project: operators-project
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
      source:
        repoURL: https://github.com/rcarrat-AI/nvidia-odh-gitops
        targetRevision: main
        path: "{{path}}"
      destination:
        server: https://kubernetes.default.svc
